name: solid_software_test_project
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  solid_lints: ^0.3.1


flutter:
  uses-material-design: true
